"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExportedFileEntity = exports.TemplateEntity = exports.AuditLogEntity = exports.CommentEntity = exports.ProjectActivityEntity = exports.ProjectStageEntity = exports.CostItemEntity = exports.ProposalSectionEntity = exports.ProposalEntity = exports.initializeDatabase = exports.AppDataSource = void 0;
var data_source_1 = require("./data-source");
Object.defineProperty(exports, "AppDataSource", { enumerable: true, get: function () { return data_source_1.AppDataSource; } });
Object.defineProperty(exports, "initializeDatabase", { enumerable: true, get: function () { return data_source_1.initializeDatabase; } });
var Proposal_entity_1 = require("./entities/Proposal.entity");
Object.defineProperty(exports, "ProposalEntity", { enumerable: true, get: function () { return Proposal_entity_1.ProposalEntity; } });
var ProposalSection_entity_1 = require("./entities/ProposalSection.entity");
Object.defineProperty(exports, "ProposalSectionEntity", { enumerable: true, get: function () { return ProposalSection_entity_1.ProposalSectionEntity; } });
var CostItem_entity_1 = require("./entities/CostItem.entity");
Object.defineProperty(exports, "CostItemEntity", { enumerable: true, get: function () { return CostItem_entity_1.CostItemEntity; } });
var ProjectStage_entity_1 = require("./entities/ProjectStage.entity");
Object.defineProperty(exports, "ProjectStageEntity", { enumerable: true, get: function () { return ProjectStage_entity_1.ProjectStageEntity; } });
var ProjectActivity_entity_1 = require("./entities/ProjectActivity.entity");
Object.defineProperty(exports, "ProjectActivityEntity", { enumerable: true, get: function () { return ProjectActivity_entity_1.ProjectActivityEntity; } });
var Comment_entity_1 = require("./entities/Comment.entity");
Object.defineProperty(exports, "CommentEntity", { enumerable: true, get: function () { return Comment_entity_1.CommentEntity; } });
var AuditLog_entity_1 = require("./entities/AuditLog.entity");
Object.defineProperty(exports, "AuditLogEntity", { enumerable: true, get: function () { return AuditLog_entity_1.AuditLogEntity; } });
var Template_entity_1 = require("./entities/Template.entity");
Object.defineProperty(exports, "TemplateEntity", { enumerable: true, get: function () { return Template_entity_1.TemplateEntity; } });
var ExportedFile_entity_1 = require("./entities/ExportedFile.entity");
Object.defineProperty(exports, "ExportedFileEntity", { enumerable: true, get: function () { return ExportedFile_entity_1.ExportedFileEntity; } });
//# sourceMappingURL=index.js.map